name: Generate API

on: push

jobs:
  generate-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate sdRDM library
        uses: JR-1991/generate-sdrdm-api@main
        with:
          library_name: MTPHandler